[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm --filter=api build"

[deploy]
startCommand = "pnpm --filter=api start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
